kind: Deployment
apiVersion: apps/v1
metadata:
  name: my-python-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-api
  template:
    metadata:
      labels:
        app: python-api
    spec:
      containers:
        - name: my-python-api
          image: ocp-python-api-git:latest
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            requests:
              memory: "50Mi"
              cpu: "10m"
          env:
            - name: APP_FILE
              value: app.py
---
kind: Service
apiVersion: v1
metadata:
  name: my-python-api
spec:
  ports:
    - name: http-8080
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: python-api
